# Generated by Django 5.2 on 2025-04-24 14:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='No images larger than 200 x 200 px.', upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
    ]
