# Generated by Django 5.2 on 2025-04-15 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_joke_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
