import random
import string
from django.utils.text import slugify

## For URLs' legs
def unique_slugs(str1, model, num_chars=50):
    """
    Return slug of num_chars length unique to model

    `str1` - The string to turn into a slug
    `model` - The model to use to check for uniqueness
    """
    slug = slugify(str1)
    ## `slugify()` converts a String to:
    # * Converts to ASCII.
    # * Converts spaces to hyphens.
    # * Removes characters that aren’t alphanumerics, underscores, or hyphens.
    # * Converts to lowercase.
    # * Strips leading and trailing whitespace.
    #### So, you have to slice (to make sure the string isn’t too long), 
    ###### and strip any trailing hyphens off.
    slug = slug[:num_chars].strip('-')
    while (True):
        dupe = model.objects.filter(slug=slug)
        if (not dupe):
            return slug
        ## If it is a DUPE, create a new slug using the first 39 chars of the existing slug,
        #### followed by a hyphen and a random string of 10 lowercase ASCII chars 
        #### generated by the random_string() function. 
        slug = slug[:39] + '-' + random_string(10)
    return 


def random_string(num_ascii_chars=10):
    letters = string.ascii_lowercase ## Get all the lowercase ASCII chars
    ## Join together random lowercase ASCII letters up to the the amount of `num_ascii_chars`
    return ''.join(random.choice(letters) for i in range(num_ascii_chars))