import random
import string
from django.utils.text import slugify

## For URLs' legs
def create_unique_url_slug(str1, model, num_chars=50):
    """
    Return slug of num_chars length unique to model

    `str1` - The string to turn into a slug
    `model` - The model to use to check for uniqueness
    """
    url_slug = slugify(str1)
    ## `slugify()` converts a String to:
    # * Converts to ASCII.
    # * Converts spaces to hyphens.
    # * Removes characters that aren’t alphanumerics, underscores, or hyphens.
    # * Converts to lowercase.
    # * Strips leading and trailing whitespace.
    #### So, you have to slice (to make sure the string isn’t too long), 
    ###### and strip any trailing hyphens off.
    url_slug = url_slug[:num_chars].strip('-')
    while (True):
        dupe = model.objects.filter(slug=url_slug)
        if (not dupe):
            return url_slug
        ## If it is a DUPE, create a new slug using the first 39 chars of the existing slug,
        #### followed by a hyphen and a random string of 10 lowercase ASCII chars 
        #### generated by the random_string() function. 
        url_slug = url_slug[:39] + '-' + get_random_string(10)
    return 


def get_random_string(num_ascii_chars=10):
    letters = string.ascii_lowercase ## Get all the lowercase ASCII chars
    ## Join together random lowercase ASCII letters up to the the amount of `num_ascii_chars`
    return ''.join(random.choice(letters) for i in range(num_ascii_chars))